Feature/ga regist update
debionetwork/debio-genetic-analyst-ui pull request #40
Opened 2022-06-03 00:24 UTC by azmimuhammad

### JIRA LINK 🟦
- https://blocksphere2020.atlassian.net/browse/DBIO-2166
- https://blocksphere2020.atlassian.net/browse/DBIO-1921

### Changelog/Description 🗒️
- Fix some defect GA regist
- unit testing GA regist step 2
- unit testing Add Service
- unit testing Edit Service

### WARNING ⚠️
- 

### Screenshoot/Video (Optional) 🖼️

2022-06-13 04:00 UTC, agustinustheo approved these changes
I already review parts where I am the code owner.

2022-06-13 06:42 UTC, hilyds requested changes

2022-06-13 06:42 UTC, hilyds commented on src/common/components/Service/AddService.vue
> +      console.log("service", service)
please remove this console.log

2022-06-13 09:55 UTC, azmimuhammad commented on src/common/components/Service/AddService.vue
> +      console.log("service", service)
updated

2022-06-14 05:08 UTC, hilyds approved these changes

2022-06-14 05:08 UTC, merged