feat: add switch network to mainet / testnet
debionetwork/debio-genetic-analyst-ui pull request #51
Opened 2022-06-17 01:07 UTC by ciniiia

### JIRA LINK 🟦
- https://blocksphere2020.atlassian.net/browse/DBIO-1262
- https://blocksphere2020.atlassian.net/browse/DBIO-2634

### Changelog/Description 🗒️
- add pop up to switch network to mainet / testnet
- adjust layout styling on generate account

### WARNING ⚠️
- n/a

### Screenshoot/Video (Optional) 🖼️

2022-06-20 05:58 UTC, hilyds approved these changes

2022-06-20 06:58 UTC, agustinustheo requested changes

2022-06-20 06:58 UTC, agustinustheo commented on src/common/lib/metamask/index.js
> +    let network = await window.ethereum.request({ method: "eth_chainId"})
Use `const` please.

2022-06-22 06:19 UTC, agustinustheo approved these changes

2022-06-22 06:20 UTC, merged