fix: unstake GA & set availability
debionetwork/debio-genetic-analyst-ui pull request #60
Opened 2022-06-28 08:47 UTC by azmimuhammad

### JIRA LINK 🟦
- https://blocksphere2020.atlassian.net/browse/DBIO-2532
- https://blocksphere2020.atlassian.net/browse/DBIO-2749
- https://blocksphere2020.atlassian.net/browse/DBIO-2751

### Changelog/Description 🗒️
- fix unstake GA
- fix set availability

### WARNING ⚠️
- 

### Screenshoot/Video (Optional) 🖼️

2022-06-28 11:09 UTC, agustinustheo requested changes
Please add the new command inside `polkadot-provider` package instead.

2022-06-29 07:10 UTC, azmimuhammad commented
> Please add the new command inside `polkadot-provider` package instead.

I added it here https://github.com/debionetwork/polkadot-provider/pull/67

2022-07-01 03:27 UTC, agustinustheo requested changes

2022-07-01 03:27 UTC, agustinustheo commented on src/common/lib/polkadot-provider/command/genetic-analyst/index.js
> +}
Please remove this and install the newest `polkadot-provider` version.

2022-07-02 04:34 UTC, agustinustheo approved these changes

2022-07-02 04:44 UTC, merged