refactor: remove metamask
debionetwork/debio-genetic-analyst-ui pull request #88
Opened 2022-08-15 09:50 UTC by bukandicki

### JIRA LINK 🟦
- https://blocksphere2020.atlassian.net/browse/DBIO-2891

### Changelog/Description 🗒️
- remove metamask
- enhancement dynamic disable menu GA on update verification

### WARNING ⚠️
- 

### Screenshoot/Video (Optional) 🖼️

2022-08-18 03:46 UTC, agustinustheo requested changes

2022-08-18 03:46 UTC, agustinustheo commented on src/store/metamask/index.js
>  const defaultState = {
Why is this file still here?

2022-08-22 11:24 UTC, ciniiia requested changes

2022-08-22 11:24 UTC, ciniiia commented on src/common/components/Navbar.vue
>      ethAccount: null,
please remove this

2022-08-22 11:24 UTC, ciniiia commented on src/common/components/Navbar.vue
>      ethRegisterAddress: null,
also this one, please remove

2022-08-22 11:24 UTC, ciniiia commented on src/common/components/Navbar.vue
>        this.ethAccount = null
please remove this unused line

2022-08-26 09:17 UTC, ciniiia approved these changes

2022-08-30 08:30 UTC, merged